# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Mod properties
mod_version = 3.2.1
core_version = 3.2.1
releaseType = BETA
changelog = Change default placeholder value for inviteURL


maven_group = de.erdbeerbaerlp.dcintegration.architectury
archives_name = dcintegration
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 26.3

# Dependencies
fabric_loader_version = 0.19.5
fabric_api_version = 0.161.0+26.3
neoforge_version = 26.3.0.48-beta

# Fabric Dependencies
fabric_permissions_api = 0.7.0
placeholder_api = 3.2.0+26.3
styled_chat = 2.14.0+26.3
vanish = 1.6.16+26.3

# NeoForge Dependencies
vanishmod = iVEuBaPo